# Generated by Django 2.2.4 on 2019-09-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hackathon',
            old_name='price_time',
            new_name='price',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='when',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
