# Generated by Django 2.2.4 on 2019-09-16 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0002_auto_20190916_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='price',
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='when',
        ),
    ]
