# Generated by Django 2.2.4 on 2019-09-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0004_auto_20190916_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='info',
            field=models.TextField(),
        ),
    ]
