# Generated by Django 2.2.4 on 2019-08-04 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userregistrationmodel',
            name='password',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AlterField(
            model_name='userregistrationmodel',
            name='user_age',
            field=models.IntegerField(blank=True, default=18),
        ),
    ]
