# Generated by Django 2.2.4 on 2019-08-29 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intro', '0002_auto_20190804_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistrationModel',
        ),
    ]
